### PR TITLE
Fix lgtm.yml to set LGTM.com Python version

### PR DESCRIPTION
**Pull request by sj**
(full disclosure: I'm on the team that built LGTM.com)

### CODE REVIEW

**Comment by erensunerr** [comment]
Thank you, I was just getting started with lgtm, do you have any tutorials?

**Comment by sj** [comment]
Happy to help! What sort of tutorials are you looking for?

**Comment by erensunerr** [comment]
I don't know video tutorials maybe I am fine with text too. But they should be for beginners. I am also looking for tutorials on doctest (a python testing framework) and sphinx. Thank you again for helping me.

**Comment by sj** [comment]
We'll be working on some videos in the near future (feel free to post your own, of course!). In the meantime: LGTM should be fairly self-explanatory. It analyses source code and gives you alerts.

Let me know if there's anything in particular that's unclear to you.

**Comment by erensunerr** [comment]
I don't know how to configure it.

**Comment by sj** [comment]
There's not much to configure :slightly_smiling_face:. You've done the right thing by pointing it at your GitHub repo, and you almost got the `lgtm.yml` configuration file right. If you merge this PR then results (if there are any alerts) will be shown on https://lgtm.com/projects/g/gerroo/SequanceFinder/alerts/?mode=tree, and any new alerts introduced in pull requests will automatically be flagged up by the automated code review.

**Comment by erensunerr** [comment]
So is it configured properly for python3?
And another question, how can I tell the server to pip install packages?

**Pull request merged**
